// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { OptimizePortfolioData, OptimizePortfolioError, OptimizePortfolioResponse } from './types.gen.js';

export const client = createClient(createConfig());

/**
 * Optimize Portfolio
 */
export const optimizePortfolio = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<OptimizePortfolioData, ThrowOnError>) => {
    return (options?.client ?? client).post<OptimizePortfolioResponse, OptimizePortfolioError, ThrowOnError>({
        ...options,
        url: '/tools/optimize'
    });
};