// This file is auto-generated by @hey-api/openapi-ts

export type __main____api___locals___Source = {
    name: string;
    cost: number;
    emissions: number;
};

export type Constraints = {
    max_cost?: number;
    max_emissions?: number;
    max_risk?: number;
};

export type datriever__smart_app__portfolio__Source = {
    cost: number;
    emissions: number;
    risk?: number;
    p_min?: number;
    p_max?: number;
    economic_risk?: number;
    operational_risk?: number;
    regulatory_risk?: number;
    environmental_risk?: number;
};

export type Gain = {
    time: string;
    gain: number;
};

export type Goals = {
    green?: number;
    cheap?: number;
    safe?: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Market = {
    id: string;
    name: string;
    location: string;
    unit: string;
};

export type MarketCandle = {
    time: string;
    open: number;
    close: number;
    high: number;
    low: number;
    marketId: string;
};

export type MarketPred = {
    time: string;
    price: number;
    marketId: string;
};

export type MarketPrices = {
    candles: Array<MarketCandle>;
    preds: Array<MarketPred>;
};

export type OptimizeParams = {
    sources: Array<datriever__smart_app__portfolio__Source>;
    goals: Goals;
    constraints: Constraints;
};

export type PortfolioSource = {
    name: string;
    cost: number;
    emissions: number;
    proportion: number;
};

export type SiteData = {
    time: string;
    site_consumption: number;
    site_production: number;
    omie_buy_price: number;
};

export type Source_Output = {
    name: string;
    cost: number;
    emissions: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type OptimizePortfolioData = {
    body: OptimizeParams;
};

export type OptimizePortfolioResponse = ((Array<(number)> | null));

export type OptimizePortfolioError = (HTTPValidationError);

export type SolarResponse = (Array<Gain>);

export type SolarError = unknown;

export type GetMarketsResponse = (Array<Market>);

export type GetMarketsError = unknown;

export type GetMarketPricesData = {
    path: {
        id: string;
    };
};

export type GetMarketPricesResponse = (MarketPrices);

export type GetMarketPricesError = (HTTPValidationError);

export type GetSourcesResponse = (Array<Source_Output>);

export type GetSourcesError = unknown;

export type UpsertSourceData = {
    body: __main____api___locals___Source;
    path: {
        id: string;
    };
};

export type UpsertSourceResponse = (unknown);

export type UpsertSourceError = (HTTPValidationError);

export type GetPortfolioResponse = (Array<PortfolioSource>);

export type GetPortfolioError = unknown;

export type AddPortfolioSourceData = {
    path: {
        id: string;
    };
    query: {
        proportion: number;
    };
};

export type AddPortfolioSourceResponse = (unknown);

export type AddPortfolioSourceError = (HTTPValidationError);

export type GetSolarDataResponse = (Array<SiteData>);

export type GetSolarDataError = unknown;

export type AddSolarDataData = {
    body: SiteData;
};

export type AddSolarDataResponse = (unknown);

export type AddSolarDataError = (HTTPValidationError);